### ISSUE TITLE
Value Error when testing realreq

### ISSUE THREAD

**Issue by Calder-Ty** [Calder-Ty/realreq#10]
I was testing realreq against iteslf, Obviously, there should be no requirements, as it installs no 3rd party packages

but i get this output instead

```
> realreq -s ./_realreq/
_realreq
_realreq
Traceback (most recent call last):
  File "/home/tyler/Envs/realreq/bin/realreq", line 8, in <module>
    sys.exit(main())
  File "/home/tyler/Envs/realreq/lib/python3.7/site-packages/_realreq/realreq.py", line 32, in main
    app()
  File "/home/tyler/Envs/realreq/lib/python3.7/site-packages/_realreq/realreq.py", line 59, in __call__
    dep_ver = _get_dependency_versions(pkgs)
  File "/home/tyler/Envs/realreq/lib/python3.7/site-packages/_realreq/realreq.py", line 155, in _get_dependency_versions
    dep, ver = line.split("==")
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by Calder-Ty** [comment]
No longer occurs
