### ISSUE TITLE
_get_dependency_versions throws value error if dependency not found

### ISSUE THREAD

**Issue by Calder-Ty** [Calder-Ty/realreq#11]
If a dependency is not found (for example it is not in the set of aliases), then a
value error is thrown `ValueError: not enough values to unpack (expected 2, got 1)`, when 
it attempts to split the string on `==`. Could we get a better error message?

**Comment by Calder-Ty** [comment]
I believe this is resolved now, Testing it I don't see this behavior

**Comment by Calder-Ty** [comment]
Saw this error again when working:

cmd: `realreq-d -s <dir>`
```
Traceback (most recent call last):
  File "[path]/realreq", line 8, in <module>
    sys.exit(main())
  File "[path]/_realreq/realreq.py", line 34, in main
    app()
  File "[path]/_realreq/realreq.py", line 66, in __call__
    dep_ver = _get_dependency_versions(pkgs)
  File "[path]/_realreq/realreq.py", line 197, in _get_dependency_versions
    dep, ver = line.split("==")
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by Calder-Ty** [comment]
Looking at this it could be caused by installs of packages from git repos e.g:
`udl @git+https://gitlab.com/<project>/udl.git@commit`

**Comment by Calder-Ty** [comment]
resolved
